version: '6'
services:
  app:
    container_name: payroll-backend
    build: .
    ports: 
      - 8081:8080 
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - fullstack-postgres


  fullstack-postgres:
    image: postgres:latest
    container_name: payroll-postgres
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - '5332:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      default:
        ipv4_address: 172.20.0.2 #make sure it's run on the 172.20.0.2

volumes:
  api:
  database_postgres:                  

# Networks to be created to facilitate communication between containers
# default network payroll-network
networks:
  default :
    external:
      name: payroll-network
